name: Build and deploy ASP.Net Core app to Azure Web App - VietSac

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1' # Make sure this version matches your project requirements
          include-prerelease: true

      - name: Build Project
        run: dotnet build --configuration Release --no-restore
        # No need to change the directory if your project is at the root

      - name: Publish Project
        run: dotnet publish --configuration Release --no-restore --output ${{env.DOTNET_ROOT}}/myapp
        # Adjust the output directory as needed

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'VietSac' # Ensure this is the name of your Azure Web App
          slot-name: 'Production' # Adjust if using a different slot or remove if not using slots
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ECB999DD5AE345F488F05AF68E301F56 }}
          package: .
